### PR TITLE
brotli-decompress received binary websocket messages

### PR DESCRIPTION
**Pull request by gefjon**
## Description of Changes

Uses [brotli.js](https://www.npmjs.com/package/brotli) to decompress incoming binary messages before Protobuf deserializing.

## API

 - [ ] This is an API breaking change to the SDK

*If the API is breaking, please state below what will break*

## Requires SpacetimeDB PRs

- https://github.com/clockworklabs/SpacetimeDB/pull/1026

### CODE REVIEW

**Comment by RReverser** [comment]
Let's switch to [brotli-dec-wasm](https://www.npmjs.com/package/brotli-dec-wasm) instead, should be faster & smaller (1.5 MB for brotli.js package vs 300KB for brotli-dec-wasm).

**Comment by RReverser** [comment]
That way we'll be able to get rid of extra Buffer dependency too, which really shouldn't be necessary on the Web.

**Comment by gefjon** [comment]
@RReverser 's version would have been better, but it turns out that making it work across different platforms (incl. the test platform) is a pain. We'll merge this now, and make improvements later.

**Comment by RReverser** [comment]
I was also wrong about 1.5MB - because you imported `/decompress` submodule directly, it's closer to 500KB, so it's not as bad as the entire module looked.

But yeah we'll revisit in future.

**Review by bfops — APPROVED** [review]
"LGTM"; this doesn't seem to have much surface area besides obviously-needed.

**Review by kazimuth — APPROVED** [review]
Yeah, LGTM.

**Pull request merged**
