### PR TITLE
modernize tooling

### LINKED ISSUE #49: Modernize typescript package

### PR DESCRIPTION
**Pull request by PuruVJ**
Closes #49.

Builds on top of Phoebe's PR. We can merge it into the PR, or into main once Protobuffectomy's merged into main

- Remove npm and yarn, replace with pnpm
- type: module
- jest -> vitest
- Build files with tsup instead of tsc
- Remove git husky, lint in GH actions
- exports map in package.json
- publint-compliant
- Ships a /min folder which has minified bundle applied in production builds
- Minimum node version set to v18(Previous LTS)
- Removed all dependencies for the end-user.

### Reduced files

Before we were shipping entire project structure as is. Now we're shipping just 5 files: 

- index.js
- index.d.ts
- index.js.map
- min/index.js
- min/index.js.map

### More deterministic

All the dependencies are now moved to devDependencies, which means end-users will not be installing those deps, they're bundled in the index.js file itself.

Required for webpack, and has the benefit of more deterministic end-user installations(If we specify brotli ^1.3 and are using 1.3.3, then only that very specific version gets shipped, whereas before, a user could have been gotten 1.3.4 which could have had a regression and cause errors)

### Smaller

Our bundle size as reported was 109KB min+brotli. Now that we control the minification and tree-shaking, it's down to just 85KB min+br. In dev mode, user's bundler will use our unminified build. When building for prod, it will use the existing minified file, which can't get much smaller, so bundler-inconsistencies while minifying are also eliminated. All this is Vite and Parcel specific off-course, Webpack isn't advanced enough for this behavior yet, it will always get the unminified build and try to minify that.

It also uses standard import/export syntax.

## What I didn't do:
- Move the tests app and examples app to Vite(There's a PR open for that)
- Integrate changesets for automatic releases and changelog. Follow-up PR for that
- Monorepo-ize the codebase, which means tests run against how the package is published rather than a local version which may not always be accurate. Follow-up PR for that

### CODE REVIEW

**Review by drogus — APPROVED** [review]
Looks great, thanks!

**Comment by PuruVJ** [comment]
Thanks, I'll still wait for Tyler's review before merging

**Comment by PuruVJ** [comment]
cc @gefjon could you test some of the stuff manually? I think you know it the best

**Comment by PuruVJ** [comment]
Putting it back to draft as putting it on `platform: browser` just cut the bundle size by 50%!! Testing to see whether it works in nodejs as well

**Pull request closed without merging**
